global: {}
service-account:
  name: default
  create: false
  sccs: ["anyuid", "privileged"]

robot-shop:
  # Registry and rpository for Docker images
  # Default is docker/robotshop/image:latest
  image:
    repo: robotshop
    version: latest
    pullPolicy: IfNotPresent

  # Alternative payment gateway URL
  # Default is https://www.paypal.com
  payment:
    gateway: null
    #gateway: https://www.worldpay.com

  # EUM configuration
  # Provide your key and set the endpoint
  eum:
    key: qUMhYJxjSv6uZh2SyqTEnw
    url: https://ec2-3-22-248-37.us-east-2.compute.amazonaws.com
    #url: https://eum-eu-west-1.instana.io
    #url: https://eum-us-west-2.instana.io

  # Pod Security Policy
  psp:
    enabled: false

  # For the mini ones minikube, minishift set to true
  nodeport: false

  # "special" Openshift. Set to true when deploying to any openshift flavour
  openshift: true

  # Storage class to use with redis statefulset.
  redis:
    storageClassName: ibmc-file-silver-gid

  ocCreateRoute: true
